#
# Copyright Â© 2016-2024 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: tb-broker-config
  namespace: thingsboard-mqtt-broker
  labels:
    name: tb-broker-config
data:
  conf: |
    export JAVA_OPTS="$JAVA_OPTS -Xmx24g -Xms24g -Xss320k -XX:+AlwaysPreTouch"
    export JAVA_OPTS="$JAVA_OPTS -Dplatform=deb -Dinstall.data_dir=/usr/share/thingsboard-mqtt-broker/data"
    export JAVA_OPTS="$JAVA_OPTS -Xlog:gc*,heap*,age*,safepoint=debug:file=/var/log/thingsboard-mqtt-broker/${TB_SERVICE_ID}-gc.log:time,uptime,level,tags:filecount=10,filesize=10M"
    export JAVA_OPTS="$JAVA_OPTS -XX:+IgnoreUnrecognizedVMOptions -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/thingsboard-mqtt-broker/${TB_SERVICE_ID}-heapdump.bin"
    export JAVA_OPTS="$JAVA_OPTS -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark"
    export JAVA_OPTS="$JAVA_OPTS -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:MaxTenuringThreshold=5"
    export JAVA_OPTS="$JAVA_OPTS -XX:+ExitOnOutOfMemoryError -XX:+UseLargePages -XX:+UseTransparentHugePages"
    export JAVA_OPTS="$JAVA_OPTS -Dio.netty.maxDirectMemory=0"
    
    # JMX
    export JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999"
    export JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1"
    
    export LOG_FILENAME=thingsboard-mqtt-broker.out
    export LOADER_PATH=/usr/share/thingsboard-mqtt-broker/conf
  logback: |
    <!DOCTYPE configuration>
    <configuration scan="true" scanPeriod="10 seconds">
    
        <appender name="fileLogAppender"
                  class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>/var/log/thingsboard-mqtt-broker/${TB_SERVICE_ID}/thingsboard-mqtt-broker.log</file>
            <rollingPolicy
                    class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
                <fileNamePattern>/var/log/thingsboard-mqtt-broker/${TB_SERVICE_ID}/thingsboard-mqtt-broker.%d{yyyy-MM-dd}.%i.log</fileNamePattern>
                <maxFileSize>100MB</maxFileSize>
                <maxHistory>30</maxHistory>
                <totalSizeCap>3GB</totalSizeCap>
            </rollingPolicy>
            <encoder>
                <pattern>%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n</pattern>
            </encoder>
        </appender>
    
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n</pattern>
            </encoder>
        </appender>
    
          <logger name="org.thingsboard.mqtt.broker.actors.client.service.connect.ConnectServiceImpl" level="INFO"/>
          <logger name="org.thingsboard.mqtt.broker.actors.client.service.disconnect.DisconnectServiceImpl" level="INFO"/>
    
        <root level="INFO">
            <appender-ref ref="fileLogAppender"/>
            <appender-ref ref="STDOUT"/>
        </root>
    
    </configuration>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tb-broker-yml-config
  labels:
    name: tb-broker-yml-config
data:
  TCP_NETTY_WORKER_GROUP_THREADS: "0"

  LISTENER_WS_ENABLED: "false"

  TB_MSG_ALL_CONSUMERS_COUNT: "4"
  TB_MSG_ALL_THREADS_COUNT: "4"
  TB_MSG_ALL_PACK_PROCESSING_TIMEOUT: "60000"
  TB_MSG_ALL_ACK_STRATEGY_TYPE: "RETRY_ALL"
  TB_MSG_ALL_ACK_STRATEGY_RETRIES: "0"
  TB_MSG_ALL_PARALLEL_PROCESSING: "false"

  TB_DEVICE_PERSISTED_MSG_CONSUMERS_COUNT: "4"
  TB_DEVICE_PERSISTED_MSG_THREADS_COUNT: "4"
  TB_DEVICE_PERSISTED_MSG_PACK_PROCESSING_TIMEOUT: "60000"
  TB_DEVICE_PERSISTED_MSG_ACK_STRATEGY_TYPE: "RETRY_ALL"
  TB_DEVICE_PERSISTED_MSG_ACK_STRATEGY_RETRIES: "0"

  TB_CLIENT_SESSION_EVENT_RESPONSE_SENDER_THREADS: "4"

  TB_PERSISTED_DOWNLINK_MSG_CONSUMERS_COUNT: "12"
  TB_PERSISTED_DOWNLINK_MSG_THREADS_COUNT: "12"

  TB_BASIC_DOWNLINK_MSG_CONSUMERS_COUNT: "0"
  TB_BASIC_DOWNLINK_MSG_THREADS_COUNT: "0"

  TB_KAFKA_DEFAULT_CONSUMER_MAX_POLL_RECORDS: "1000"
  TB_KAFKA_DEFAULT_CONSUMER_MAX_PARTITION_FETCH_BYTES: "16777216"
  TB_KAFKA_DEFAULT_CONSUMER_FETCH_MAX_BYTES: "134217728"

  TB_KAFKA_DEFAULT_PRODUCER_ACKS: "1"
  TB_KAFKA_DEFAULT_PRODUCER_BATCH_SIZE: "8192"
  TB_KAFKA_DEFAULT_PRODUCER_LINGER_MS: "10"
  TB_KAFKA_DEFAULT_PRODUCER_BUFFER_MEMORY: "33554432"
  TB_KAFKA_DEFAULT_COMPRESSION_TYPE: "none"

  TB_KAFKA_MSG_ALL_TOPIC_PROPERTIES: "retention.ms:604800000;segment.bytes:26214400;retention.bytes:2147483648;partitions:20;replication.factor:1"
  TB_KAFKA_MSG_ALL_ADDITIONAL_CONSUMER_CONFIG: "fetch.min.bytes:128"
  TB_KAFKA_MSG_ALL_ADDITIONAL_PRODUCER_CONFIG: ""

  TB_KAFKA_DEVICE_PERSISTED_MSG_TOPIC_PROPERTIES: "retention.ms:604800000;segment.bytes:26214400;retention.bytes:1048576000;partitions:20;replication.factor:1"
  TB_KAFKA_DEVICE_PERSISTED_MSG_ADDITIONAL_CONSUMER_CONFIG: "fetch.min.bytes:128"
  TB_KAFKA_DEVICE_PERSISTED_MSG_ADDITIONAL_PRODUCER_CONFIG: ""

  TB_KAFKA_PERSISTED_DOWNLINK_MSG_TOPIC_PROPERTIES: "retention.ms:604800000;segment.bytes:26214400;retention.bytes:1048576000;partitions:12;replication.factor:1"
  TB_KAFKA_PERSISTED_DOWNLINK_MSG_ADDITIONAL_CONSUMER_CONFIG: "fetch.min.bytes:128"
  TB_KAFKA_PERSISTED_DOWNLINK_MSG_ADDITIONAL_PRODUCER_CONFIG: "linger.ms:10;batch.size:8192"

  ACTORS_SYSTEM_THROUGHPUT: "5"
  ACTORS_SYSTEM_PERSISTED_DEVICE_DISPATCHER_POOL_SIZE: "8"
  ACTORS_SYSTEM_CLIENT_DISPATCHER_POOL_SIZE: "8"
  ACTORS_RULE_MAIL_THREAD_POOL_SIZE: "1"
  ACTORS_RULE_MAIL_PASSWORD_RESET_THREAD_POOL_SIZE: "1"

  SQL_UNAUTHORIZED_CLIENT_INSERT_BATCH_THREADS: "1"
  SQL_UNAUTHORIZED_CLIENT_DELETE_BATCH_THREADS: "1"

  MQTT_MSG_SUBSCRIPTIONS_PARALLEL_PROCESSING: "false"
  MQTT_KEEP_ALIVE_MONITORING_DELAY_MS: "60000"

  MQTT_HANDLER_ALL_MSG_CALLBACK_THREADS: "6"
  MQTT_HANDLER_DEVICE_MSG_CALLBACK_THREADS: "6"
  MQTT_HANDLER_DOWNLINK_MSG_CALLBACK_THREADS: "6"
  MQTT_HANDLER_APP_MSG_CALLBACK_THREADS: "0"

  CACHE_STATS_ENABLED: "false"
  STATS_ENABLED: "false"
  APPLICATION_PROCESSOR_STATS_ENABLED: "false"
  HISTORICAL_DATA_REPORT_ENABLED: "false"
  TB_KAFKA_CONSUMER_STATS_ENABLED: "false"

  MQTT_FLOW_CONTROL_ENABLED: "false"

  MQTT_MAX_IN_FLIGHT_MSGS: "1000"

  REDIS_LETTUCE_CMDS_AUTO_FLUSH_ENABLED: "false"
  REDIS_LETTUCE_BUFFERED_CMDS_COUNT: "1000"
  REDIS_LETTUCE_FLUSH_INTERVAL_MS: "3"

  TB_CLIENT_SESSION_EVENT_BATCH_WAIT_MS: "90000"
  TB_CLIENT_SESSION_EVENT_MAX_PENDING_REQUESTS: "120000"
  TB_CLIENT_SESSION_EVENT_CONSUMERS_COUNT: "3"
